version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-HLRQuQtVdJGtNcNxACuuxNMGqPGtbLoB}
      MYSQL_DATABASE: railway
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD:-HLRQuQtVdJGtNcNxACuuxNMGqPGtbLoB}
      - SERVER_PORT=8082
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME:-pratikmalviya2974@gmail.com}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD:-your_app_password}
    ports:
      - "8082:8082"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8082/api
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 