version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-HLRQuQtVdJGtNcNxACuuxNMGqPGtbLoB}
      MYSQL_DATABASE: railway
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD:-HLRQuQtVdJGtNcNxACuuxNMGqPGtbLoB}
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 